// Mock data for development
export const mockPOIs = [
  {
    id: 1,
    name: 'Chè Khúc Bạch Thanh Xuân',
    description: 'Chè khúc bạch truyền thống với nước dùng đặc biệt',
    price: '$$',
    image: '/images/poi/1.jpg',
    category: 'Chè',
    location: { lat: 10.7965, lng: 106.7490 },
    rating: 4.5,
    phone: '0123456789',
    website: 'https://example.com',
    audio: '/audio/che-khuc-bach.mp3',
    narration: {
      sourceLanguage: 'vi',
      content: 'Chè Khúc Bạch Thanh Xuân nổi bật với độ mềm mịn của khúc bạch và vị ngọt thanh cân bằng.\n\nMón được phục vụ lạnh, phù hợp sau khi thưởng thức các món chính nhiều đạm. Chủ quán khuyên dùng cùng topping hạnh nhân để tăng độ bùi.',
    },
    hours: '7:00 - 22:00',
    address: '45 Đường Vĩnh Khánh, Phường 8, Quận 4, Hồ Chí Minh, Việt Nam',
  },
  {
    id: 2,
    name: 'Phở Hòa Pasteur',
    description: 'Phở truyền thống với nước dùng được nấu từ xương trong nhiều giờ',
    price: '$$',
    image: '/images/poi/2.png',
    category: 'Phở',
    location: { lat: 10.7970, lng: 106.7500 },
    rating: 4.7,
    phone: '0987654321',
    website: 'https://example.com',
    audio: '/audio/pho-hoa.mp3',
    narration: {
      sourceLanguage: 'vi',
      content: 'Phở Hòa Pasteur có nước dùng ninh từ xương trong nhiều giờ, tạo chiều sâu vị umami rõ rệt.\n\nĐiểm đáng chú ý là phần bánh phở mềm vừa, không nát, kết hợp tốt với thịt tái và các loại rau ăn kèm.',
    },
    hours: '6:00 - 22:00',
    address: '58 Đường Vĩnh Khánh, Phường 8, Quận 4, Hồ Chí Minh, Việt Nam',
  },
  {
    id: 3,
    name: 'Bánh Mì Huyền Hoa',
    description: 'Bánh mì giòn với nhân thịt và rau sống tươi',
    price: '$',
    image: '/images/poi/3.png',
    category: 'Bánh Mì',
    location: { lat: 10.7950, lng: 106.7480 },
    rating: 4.6,
    phone: '0111111111',
    website: 'https://example.com',
    audio: '/audio/banh-mi-huyen-hoa.mp3',
    narration: {
      sourceLanguage: 'vi',
      content: 'Bánh Mì Huyền Hoa là lựa chọn nhanh gọn cho bữa sáng hoặc bữa xế.\n\nLớp vỏ giòn nhẹ, nhân thịt đậm vị, kết hợp đồ chua giúp tổng thể cân bằng và dễ ăn.',
    },
    hours: '6:30 - 20:00',
    address: '72 Đường Vĩnh Khánh, Phường 8, Quận 4, Hồ Chí Minh, Việt Nam',
  },
  {
    id: 4,
    name: 'Cafe Sữa Đá Truyền Thống',
    description: 'Cà phê sữa đá với cà phê rang nguyên chất',
    price: '$',
    image: '/images/poi/4.png',
    category: 'Cafe',
    location: { lat: 10.7940, lng: 106.7470 },
    rating: 4.4,
    phone: '0222222222',
    website: 'https://example.com',
    audio: '/audio/cafe-sua-da.mp3',
    narration: {
      sourceLanguage: 'vi',
      content: 'Cà phê sữa đá ở đây dùng hạt rang đậm, hương thơm rõ, hậu vị kéo dài.\n\nNếu muốn vị nhẹ hơn, bạn có thể yêu cầu thêm đá hoặc giảm lượng sữa đặc.',
    },
    hours: '6:00 - 23:00',
    address: '83 Đường Vĩnh Khánh, Phường 8, Quận 4, Hồ Chí Minh, Việt Nam',
  },
  {
    id: 5,
    name: 'Com Tấm Móc',
    description: 'Cơm tấm với thịt nướng và trứng ốp la',
    price: '$',
    image: '/images/poi/5.jpg',
    category: 'Cơm Tấm',
    location: { lat: 10.7930, lng: 106.7460 },
    rating: 4.5,
    phone: '0333333333',
    website: 'https://example.com',
    audio: '/audio/com-tam-moc.mp3',
    narration: {
      sourceLanguage: 'vi',
      content: 'Cơm Tấm Móc có hạt cơm tơi, thơm, ăn cùng sườn nướng và trứng ốp la.\n\nNước mắm pha theo vị miền Nam, thiên ngọt nhẹ, phù hợp đa số thực khách quốc tế.',
    },
    hours: '10:00 - 20:00',
    address: '96 Đường Vĩnh Khánh, Phường 8, Quận 4, Hồ Chí Minh, Việt Nam',
  },
  {
    id: 6,
    name: 'Mì Cay Hà Nội',
    description: 'Mì cay ngon cay với nước dùng đậm đà',
    price: '$',
    image: '/images/poi/6.jpg',
    category: 'Mì',
    location: { lat: 10.7975, lng: 106.7510 },
    rating: 4.3,
    phone: '0444444444',
    website: 'https://example.com',
    audio: '/audio/mi-cay.mp3',
    narration: {
      sourceLanguage: 'vi',
      content: 'Mì cay Hà Nội có nước dùng đậm đà, phù hợp người thích vị cay trung bình đến cao.\n\nBạn có thể chọn cấp độ cay khi gọi món để phù hợp khẩu vị cá nhân.',
    },
    hours: '11:00 - 22:00',
    address: '109 Đường Vĩnh Khánh, Phường 8, Quận 4, Hồ Chí Minh, Việt Nam',
  },
  {
    id: 7,
    name: 'Bun Chả Hang Than',
    description: 'Bún chả với thịt nướng trên than hoa',
    price: '$$',
    image: '/images/poi/7.jpg',
    category: 'Bún Chả',
    location: { lat: 10.7955, lng: 106.7520 },
    rating: 4.6,
    phone: '0555555555',
    website: 'https://example.com',
    audio: '/audio/bun-cha.mp3',
    narration: {
      sourceLanguage: 'vi',
      content: 'Bún Chả Hàng Than phục vụ chả nướng thơm mùi than hoa, ăn cùng bún và rau sống.\n\nNước chấm chua ngọt là linh hồn của món, nên trộn đều trước khi thưởng thức.',
    },
    hours: '11:00 - 20:00',
    address: '121 Đường Vĩnh Khánh, Phường 8, Quận 4, Hồ Chí Minh, Việt Nam',
  },
  {
    id: 8,
    name: 'Xôi Nếp Hòa',
    description: 'Xôi nếp truyền thống với nhiều loại topping',
    price: '$',
    image: '/images/poi/8.jpg',
    category: 'Xôi',
    location: { lat: 10.7985, lng: 106.7445 },
    rating: 4.4,
    phone: '0666666666',
    website: 'https://example.com',
    audio: '/audio/xoi-nep.mp3',
    narration: {
      sourceLanguage: 'vi',
      content: 'Xôi Nếp Hòa có nền nếp dẻo, thơm, phù hợp dùng cho bữa sáng sớm.\n\nQuán có nhiều topping để lựa chọn, từ mặn đến ngọt, giúp dễ cá nhân hóa phần ăn.',
    },
    hours: '5:00 - 11:00',
    address: '134 Đường Vĩnh Khánh, Phường 8, Quận 4, Hồ Chí Minh, Việt Nam',
  },
  {
    id: 9,
    name: 'Egg Coffee Hoan Kiem',
    description: 'Cà phê trứng nổi tiếng kiểu Hà Nội cổ',
    price: '$',
    image: '/images/poi/9.jpg',
    category: 'Cafe',
    location: { lat: 10.7920, lng: 106.7485 },
    rating: 4.8,
    phone: '0777777777',
    website: 'https://example.com',
    audio: '/audio/egg-coffee.mp3',
    narration: {
      sourceLanguage: 'vi',
      content: 'Egg Coffee Hoàn Kiếm nổi tiếng với lớp kem trứng bông mịn trên nền cà phê đậm.\n\nThực khách nên uống khi còn ấm để cảm nhận rõ sự hòa quyện của hai lớp vị.',
    },
    hours: '7:00 - 23:00',
    address: '147 Đường Vĩnh Khánh, Phường 8, Quận 4, Hồ Chí Minh, Việt Nam',
  },
  {
    id: 10,
    name: 'Bánh Cuốn Phở Cuốn',
    description: 'Bánh cuốn nóng với nhân thịt và mộc nhân',
    price: '$',
    image: '/images/poi/10.jpg',
    category: 'Bánh Cuốn',
    location: { lat: 10.7910, lng: 106.7505 },
    rating: 4.5,
    phone: '0888888888',
    website: 'https://example.com',
    audio: '/audio/banh-cuon.mp3',
    narration: {
      sourceLanguage: 'vi',
      content: 'Bánh Cuốn Phở Cuốn có lớp bánh mỏng, mềm, phần nhân thịt vừa vị và không quá béo.\n\nMón phù hợp cho người thích khẩu phần nhẹ nhưng vẫn đủ năng lượng cho hành trình khám phá.',
    },
    hours: '6:00 - 21:00',
    address: '159 Đường Vĩnh Khánh, Phường 8, Quận 4, Hồ Chí Minh, Việt Nam',
  },
];

export const mockTours = [
  {
    id: 1,
    name: 'Tour Sáng - Ăn sáng cùng Food Tour',
    description: 'Khám phá các quán ăn sáng nổi tiếng tại khu Vĩnh Khánh',
    pois: [1, 8, 10],
    duration: '2 giờ',
    language: 'VI',
    status: 'published',
    updatedAt: '2026-03-28',
    version: 2,
    versions: [
      { v: 1, pois: [1, 8], updatedAt: '2026-03-10' },
      { v: 2, pois: [1, 8, 10], updatedAt: '2026-03-28' },
    ],
  },
  {
    id: 2,
    name: 'Tour Tối - Trải nghiệm ẩm thực đêm',
    description: 'Thưởng thức các đặc sản buổi tối tại Vĩnh Khánh',
    pois: [2, 7, 4, 9],
    duration: '3 giờ',
    language: 'EN',
    status: 'published',
    updatedAt: '2026-04-01',
    version: 1,
    versions: [
      { v: 1, pois: [2, 7, 4, 9], updatedAt: '2026-04-01' },
    ],
  },
  {
    id: 3,
    name: 'Tour Ăn Vặt Vĩnh Khánh',
    description: 'Khám phá các món ăn vặt ngon tại khu phố ẩm thực',
    pois: [3, 5, 6, 2, 7],
    duration: '2.5 giờ',
    language: 'VI',
    status: 'draft',
    updatedAt: '2026-04-02',
    version: 1,
    versions: [
      { v: 1, pois: [3, 5, 6, 2, 7], updatedAt: '2026-04-02' },
    ],
  },
  {
    id: 4,
    name: 'Tour Đầy Đủ - Hành Trình Ẩm Thực',
    description: 'Tour trọn ngày khám phá toàn bộ khu ẩm thực Vĩnh Khánh',
    pois: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    duration: '6 giờ',
    language: 'VI',
    status: 'draft',
    updatedAt: '2026-04-03',
    version: 1,
    versions: [
      { v: 1, pois: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], updatedAt: '2026-04-03' },
    ],
  },
];

export const mockUser = {
  email: 'user@example.com',
  language: 'vi',
  role: 'visitor',
};
