// Mock data for development
export const mockPOIs = [
  {
    id: 1,
    name: 'Chè Khúc Bạch Thanh Xuân',
    description: 'Chè khúc bạch truyền thống với nước dùng đặc biệt',
    price: '$$',
    image: '/images/che-khuc-bach.jpg',
    category: 'Chè',
    location: { lat: 10.7965, lng: 106.7490 },
    rating: 4.5,
    phone: '0123456789',
    website: 'https://example.com',
    audio: '/audio/che-khuc-bach.mp3',
    hours: '7:00 - 22:00',
    address: 'Thanh Xuân, Hà Nội',
  },
  {
    id: 2,
    name: 'Phở Hòa Pasteur',
    description: 'Phở truyền thống với nước dùng được nấu từ xương trong nhiều giờ',
    price: '$$',
    image: '/images/pho-hoa.jpg',
    category: 'Phở',
    location: { lat: 10.7970, lng: 106.7500 },
    rating: 4.7,
    phone: '0987654321',
    website: 'https://example.com',
    audio: '/audio/pho-hoa.mp3',
    hours: '6:00 - 22:00',
    address: 'Pasteur, Hà Nội',
  },
  {
    id: 3,
    name: 'Bánh Mì Huyền Hoa',
    description: 'Bánh mì giòn với nhân thịt và rau sống tươi',
    price: '$',
    image: '/images/banh-mi-huyen-hoa.jpg',
    category: 'Bánh Mì',
    location: { lat: 10.7950, lng: 106.7480 },
    rating: 4.6,
    phone: '0111111111',
    website: 'https://example.com',
    audio: '/audio/banh-mi-huyen-hoa.mp3',
    hours: '6:30 - 20:00',
    address: 'Huyền Hoa, Hà Nội',
  },
  {
    id: 4,
    name: 'Cafe Sữa Đá Truyền Thống',
    description: 'Cà phê sữa đá với cà phê rang nguyên chất',
    price: '$',
    image: '/images/cafe-sua-da.jpg',
    category: 'Cafe',
    location: { lat: 10.7940, lng: 106.7470 },
    rating: 4.4,
    phone: '0222222222',
    website: 'https://example.com',
    audio: '/audio/cafe-sua-da.mp3',
    hours: '6:00 - 23:00',
    address: 'Kim Mã, Hà Nội',
  },
  {
    id: 5,
    name: 'Com Tấm Móc',
    description: 'Cơm tấm với thịt nướng và trứng ốp la',
    price: '$',
    image: '/images/com-tam-moc.jpg',
    category: 'Cơm Tấm',
    location: { lat: 10.7930, lng: 106.7460 },
    rating: 4.5,
    phone: '0333333333',
    website: 'https://example.com',
    audio: '/audio/com-tam-moc.mp3',
    hours: '10:00 - 20:00',
    address: 'Móc, Hà Nội',
  },
  {
    id: 6,
    name: 'Mì Cay Hà Nội',
    description: 'Mì cay ngon cay với nước dùng đậm đà',
    price: '$',
    image: '/images/mi-cay.jpg',
    category: 'Mì',
    location: { lat: 10.7975, lng: 106.7510 },
    rating: 4.3,
    phone: '0444444444',
    website: 'https://example.com',
    audio: '/audio/mi-cay.mp3',
    hours: '11:00 - 22:00',
    address: 'Trần Hưng Đạo, Hà Nội',
  },
  {
    id: 7,
    name: 'Bun Chả Hang Than',
    description: 'Bún chả với thịt nướng trên than hoa',
    price: '$$',
    image: '/images/bun-cha.jpg',
    category: 'Bún Chả',
    location: { lat: 10.7955, lng: 106.7520 },
    rating: 4.6,
    phone: '0555555555',
    website: 'https://example.com',
    audio: '/audio/bun-cha.mp3',
    hours: '11:00 - 20:00',
    address: 'Hàng Than, Hà Nội',
  },
  {
    id: 8,
    name: 'Xôi Nếp Hòa',
    description: 'Xôi nếp truyền thống với nhiều loại topping',
    price: '$',
    image: '/images/xoi-nep.jpg',
    category: 'Xôi',
    location: { lat: 10.7985, lng: 106.7445 },
    rating: 4.4,
    phone: '0666666666',
    website: 'https://example.com',
    audio: '/audio/xoi-nep.mp3',
    hours: '5:00 - 11:00',
    address: 'Hòa Mã, Hà Nội',
  },
  {
    id: 9,
    name: 'Egg Coffee Hoan Kiem',
    description: 'Cà phê trứng nổi tiếng kiểu Hà Nội cổ',
    price: '$',
    image: '/images/egg-coffee.jpg',
    category: 'Cafe',
    location: { lat: 10.7920, lng: 106.7485 },
    rating: 4.8,
    phone: '0777777777',
    website: 'https://example.com',
    audio: '/audio/egg-coffee.mp3',
    hours: '7:00 - 23:00',
    address: 'Hoàn Kiếm, Hà Nội',
  },
  {
    id: 10,
    name: 'Bánh Cuốn Phở Cuốn',
    description: 'Bánh cuốn nóng với nhân thịt và mộc nhân',
    price: '$',
    image: '/images/banh-cuon.jpg',
    category: 'Bánh Cuốn',
    location: { lat: 10.7910, lng: 106.7505 },
    rating: 4.5,
    phone: '0888888888',
    website: 'https://example.com',
    audio: '/audio/banh-cuon.mp3',
    hours: '6:00 - 21:00',
    address: 'Trần Thánh Tông, Hà Nội',
  },
];

export const mockTours = [
  {
    id: 1,
    name: 'Tour Sáng - Ăn sáng cùng Food Tour',
    description: 'Khám phá các quán ăn sáng nổi tiếng',
    pois: [1, 8, 10],
    duration: '2 giờ',
  },
  {
    id: 2,
    name: 'Tour Tối - Trải nghiệm ẩm thực đêm',
    description: 'Thưởng thức các đặc sản tối',
    pois: [2, 7, 4, 9],
    duration: '3 giờ',
  },
  {
    id: 3,
    name: 'Tour Ăn Vặt Hà Nội',
    description: 'Khám phá các món ăn vặt ngon của Hà Nội',
    pois: [3, 5, 6, 2, 7],
    duration: '2.5 giờ',
  },
  {
    id: 4,
    name: 'Tour Đầy Đủ - Hành Trình Ẩm Thực',
    description: 'Tour trọn ngày khám phá ẩm thực Hà Nội',
    pois: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    duration: '6 giờ',
  },
];

export const mockUser = {
  email: 'user@example.com',
  language: 'vi',
  role: 'visitor',
};
